Repository jacklvd/LifePubUC, pull requests merged in 2025-04, with the labels that each got.

#48 Add footer to landing page
  app/client/app/(dashboard)/categories/components/item-card.tsx
  app/client/app/(dashboard)/categories/components/items-grid.tsx
  app/client/app/(dashboard)/categories/page.tsx
  app/client/app/(dashboard)/layout.tsx
  app/client/app/organization/home/components/stats-overview.tsx
  app/client/app/organization/home/page.tsx
  app/client/app/organization/items/create/components/item-detail-section.tsx
  app/client/app/organization/items/create/components/photo-section.tsx
  app/client/app/organization/items/create/components/pricing-section.tsx
  app/client/app/organization/items/create/components/review-section.tsx
  app/client/app/organization/items/create/page.tsx
  app/client/app/organization/layout.tsx
  app/client/components/ui/footer.tsx
  app/client/constants/index.ts
  app/client/lib/actions/item-actions.ts
  app/client/lib/actions/transaction-actions.ts
  app/server/src/controllers/itemController.ts
  app/server/src/controllers/paymentController.ts
  app/server/src/controllers/transactionController.ts
  app/server/src/index.ts
  app/server/src/lib/validateSeller.ts
  app/server/src/models/itemSchema.ts
  app/server/src/models/transactionSchema.ts
  app/server/src/routes/itemRoute.ts
  app/server/src/routes/sellerRoute.ts
  app/server/src/routes/transactionRoute.ts
Labels: documentation, duplicate, enhancement, dependencies

#51 modify lots of thing
  Senior_Design_2024-2025.code-workspace
  app/client/app/(dashboard)/components/carousel.tsx
  app/client/app/(dashboard)/components/creatorcta.tsx
  app/client/app/(dashboard)/components/event-card.tsx
  app/client/app/(dashboard)/components/event-grid.tsx
  app/client/app/(dashboard)/components/location-selector.tsx
  app/client/app/(dashboard)/components/locations.tsx
  app/client/app/(dashboard)/components/smaller-card.tsx
  app/client/app/(dashboard)/components/upcoming.tsx
  app/client/app/(dashboard)/page.tsx
  app/client/app/organization/events/[eventId]/publish/page.tsx
  app/client/app/organization/events/components/event-calendar-popup.tsx
  app/client/app/organization/events/components/event-card.tsx
  app/client/app/organization/events/components/event-leftside-bar.tsx
  app/client/app/organization/home/components/products-section.tsx
  app/client/app/organization/home/components/stats-overview.tsx
  app/client/app/organization/home/page.tsx
  app/client/app/organization/items/page.tsx
  app/client/app/organization/reports/components/items-overview.tsx
  app/client/app/organization/reports/components/monthly-comparison.tsx
  app/client/app/organization/reports/components/revenue-source.tsx
  app/client/app/organization/reports/components/revenue.tsx
  app/client/app/organization/reports/page.tsx
  app/client/components/icons.tsx
  app/client/components/ui/alert.tsx
  app/client/components/ui/footer.tsx
  app/client/lib/actions/event-actions.ts
  app/client/lib/actions/item-actions.ts
  app/client/lib/actions/location-actions.ts
  app/client/lib/date-formatter.ts
  app/client/lib/utils.ts
  app/client/next.config.ts
  app/client/types/types.d.ts
  app/server/src/controllers/itemController.ts
  app/server/src/controllers/transactionController.ts
  app/server/src/lib/validateSeller.ts
  app/server/src/routes/itemRoute.ts
Labels: enhancement, javascript

#52 Update readme for final report
  .gitignore
  README.md
  Senior_Design_2024-2025.code-workspace
  app/client/app/(dashboard)/categories/[itemId]/page.tsx
  app/client/app/(dashboard)/categories/components/categories-section.tsx
  app/client/app/(dashboard)/categories/components/item-detail.tsx
  app/client/app/(dashboard)/categories/components/pagination.tsx
  app/client/app/(dashboard)/categories/components/sort-and-filter-bar.tsx
  app/client/app/(dashboard)/categories/components/testimonials.tsx
  app/client/app/(dashboard)/categories/page.tsx
  app/client/app/(dashboard)/profile/bank/page.tsx
  app/client/app/(dashboard)/profile/layout.tsx
  app/client/app/organization/items/page.tsx
  app/client/components/icons.tsx
  app/client/components/shop-maker.tsx
  app/client/context/event-context.tsx
  image-1.png
  image-2.png
  image-3.png
  image.png
Labels: documentation, dependencies

#53 clean up and modify a lot
  README.md
  Senior_Design_2024-2025.code-workspace
  app/client/app/(dashboard)/categories/components/pagination.tsx
  app/client/app/(dashboard)/categories/components/sort-and-filter-bar.tsx
  app/client/app/(dashboard)/components/shop-maker.tsx
  app/client/app/(dashboard)/components/upcoming.tsx
  app/client/app/(dashboard)/page.tsx
  app/client/app/organization/components/organization-sidebar.tsx
  app/client/app/organization/home/page.tsx
  app/client/app/organization/items/components/alert-display.tsx
  app/client/app/organization/items/components/bulk-actions.tsx
  app/client/app/organization/items/components/empty-state.tsx
  app/client/app/organization/items/components/filter-tools.tsx
  app/client/app/organization/items/components/index.ts
  app/client/app/organization/items/components/item-card.tsx
  app/client/app/organization/items/components/item-header.tsx
  app/client/app/organization/items/components/item-list.tsx
  app/client/app/organization/items/components/loading-state.tsx
  app/client/app/organization/items/components/pagination.tsx
  app/client/app/organization/items/page.tsx
  app/client/app/organization/layout.tsx
  app/client/app/organization/onboarding/page.tsx
  app/client/app/organization/orders/page.tsx
  app/client/app/organization/settings/page.tsx
  app/client/components/icons.tsx
  app/client/components/navbar.tsx
  app/client/components/ui/footer.tsx
  app/client/context/onboarding.tsx
  app/client/lib/actions/item-actions.ts
  app/client/lib/actions/stripe-actions.ts
  app/client/lib/axios.ts
  app/client/store/ticketStore.ts
  app/client/types/types.d.ts
  app/server/src/controllers/sellerController.ts
  app/server/src/controllers/transactionController.ts
  assets/UserManual.md
  assets/User_Stories.md
  assets/biography/Hoang_Nguyen_biography.md
  assets/biography/Jack_Biography.md
  assets/biography/QuanPhamProfessionalBio.md
  assets/biography/quan.md
  assets/image-1.png
  assets/image-2.png
  assets/image-3.png
  assets/image.png
Labels: documentation, enhancement
