Repository jacklvd/LifePubUC, pull requests merged in 2025-03, with the labels that each got.

#33 Add payment integration using stripe
  app/client/app/(dashboard)/cart/page.tsx
  app/client/app/(dashboard)/checkout/components/checkout-form.tsx
  app/client/app/(dashboard)/checkout/components/payment-content.tsx
  app/client/app/(dashboard)/checkout/components/stripe-provider.tsx
  app/client/app/(dashboard)/checkout/page.tsx
  app/client/app/(dashboard)/checkout/return/page.tsx
  app/client/app/(dashboard)/layout.tsx
  app/client/app/layout.tsx
  app/client/app/organization/home/page.tsx
  app/client/app/organization/onboarding/page.tsx
  app/client/auth.ts
  app/client/components/navbar.tsx
  app/client/constants/index.ts
  app/client/lib/actions/stripe-actions.ts
  app/client/lib/axios.ts
  app/client/next.config.ts
  app/client/types/types.d.ts
  app/server/.env.example
  app/server/package.json
  app/server/src/controllers/authController.ts
  app/server/src/controllers/courseController.ts
  app/server/src/controllers/paymentController.ts
  app/server/src/controllers/userController.ts
  app/server/src/index.ts
  app/server/src/models/itemSchema.ts
  app/server/src/models/transactionSchema.ts
  app/server/src/models/userSchema.ts
  app/server/src/routes/paymentRoute.ts
  app/server/src/routes/userRoute.ts
  app/server/yarn.lock
Labels: enhancement, help wanted, good first issue

#36 Create Event Flow
  .github/workflows/prettier.yml
  app/client/app/(auth)/sign-in/page.tsx
  app/client/app/(auth)/sign-up/page.tsx
  app/client/app/(auth)/verify-credential/page.tsx
  app/client/app/(dashboard)/cart/page.tsx
  app/client/app/(dashboard)/categories/page.tsx
  app/client/app/(dashboard)/checkout/page.tsx
  app/client/app/(dashboard)/checkout/return/page.tsx
  app/client/app/layout.tsx
  app/client/app/organization/events/create/page.tsx
  app/client/app/organization/events/page.tsx
  app/client/app/organization/items/create/page.tsx
  app/client/app/organization/onboarding/page.tsx
  app/client/components/category-ui/category-card.tsx
  app/client/components/category-ui/item-card.tsx
  app/client/components/category-ui/item-list.tsx
  app/client/components/checkout-ui/checkout-form.tsx
  app/client/components/checkout-ui/payment-content.tsx
  app/client/components/checkout-ui/stripe-provider.tsx
  app/client/components/event-ui/event-additional.tsx
  app/client/components/event-ui/event-agenda.tsx
  app/client/components/event-ui/event-calendar.tsx
  app/client/components/event-ui/event-datetime-picker.tsx
  app/client/components/event-ui/event-insight.tsx
  app/client/components/event-ui/event-leftside-bar.tsx
  app/client/components/event-ui/event-location.tsx
  app/client/components/event-ui/event-photo.tsx
  app/client/components/event-ui/event-title-picker.tsx
  app/client/components/icons.tsx
  app/client/components/navbar.tsx
  app/client/components/organization-sidebar.tsx
  app/client/components/timeout.tsx
  app/client/components/ui/accordion.tsx
  app/client/components/ui/dialog.tsx
  app/client/components/ui/radio-group.tsx
  app/client/components/ui/scroll-area.tsx
  app/client/components/ui/select.tsx
  app/client/components/ui/time-picker.tsx
  app/client/constants/index.ts
  app/client/lib/actions/auth-actions.ts
  app/client/lib/actions/event-action.ts
  app/client/lib/validations.ts
  app/client/next.config.ts
  app/client/package.json
  app/client/tailwind.config.ts
  app/client/tsconfig.json
  app/client/types/types.d.ts
  app/client/yarn.lock
  app/server/config/env.ts
  app/server/src/controllers/courseController.ts
  app/server/src/controllers/eventController.ts
  app/server/src/controllers/itemController.ts
  app/server/src/controllers/paymentController.ts
  app/server/src/controllers/userController.ts
  app/server/src/index.ts
  app/server/src/models/eventSchema.ts
  app/server/src/routes/eventRoute.ts
  app/server/src/routes/userRoute.ts
Labels: enhancement, good first issue, dependencies

#37 added many things
  app/client/app/(dashboard)/layout.tsx
  app/client/app/organization/events/[eventId]/edit/page.tsx
  app/client/app/organization/events/[eventId]/page.tsx
  app/client/app/organization/events/[eventId]/preview-publish/page.tsx
  app/client/app/organization/events/[eventId]/publish/page.tsx
  app/client/app/organization/events/[eventId]/ticket/page.tsx
  app/client/app/organization/events/create/page.tsx
  app/client/app/organization/events/layout.tsx
  app/client/app/organization/events/page.tsx
  app/client/components/event-fallback.tsx
  app/client/components/event-form.tsx
  app/client/components/event-ui/calendar-header.tsx
  app/client/components/event-ui/event-additional.tsx
  app/client/components/event-ui/event-agenda.tsx
  app/client/components/event-ui/event-calendar-popup.tsx
  app/client/components/event-ui/event-calendar.tsx
  app/client/components/event-ui/event-card.tsx
  app/client/components/event-ui/event-flow-layout.tsx
  app/client/components/event-ui/event-form-ui.tsx
  app/client/components/event-ui/event-insight.tsx
  app/client/components/event-ui/event-leftside-bar.tsx
  app/client/components/event-ui/event-list.tsx
  app/client/components/event-ui/event-title-picker.tsx
  app/client/components/event-ui/month-view.tsx
  app/client/components/event-ui/week-view.tsx
  app/client/components/icons.tsx
  app/client/components/navbar.tsx
  app/client/components/organization-sidebar.tsx
  app/client/components/ticket-ui.tsx
  app/client/components/ticket-ui/capactity-card.tsx
  app/client/components/ticket-ui/empty-ticket-state.tsx
  app/client/components/ticket-ui/sidebar-content.tsx
  app/client/components/ticket-ui/ticket-card.tsx
  app/client/components/ticket-ui/ticket-day-picker.tsx
  app/client/components/ticket-ui/ticket-dialogs.tsx
  app/client/components/ticket-ui/ticket-form.tsx
  app/client/components/ui/checkbox.tsx
  app/client/components/ui/progress.tsx
  app/client/constants/index.ts
  app/client/context/event-context.tsx
  app/client/hooks/use-debouce.ts
  app/client/hooks/use-event.ts
  app/client/hooks/use-eventcalendar.ts
  app/client/hooks/use-eventprocessing.ts
  app/client/hooks/use-ticket.ts
  app/client/lib/actions/event-action.ts
  app/client/lib/actions/event-actions.ts
  app/client/lib/actions/ticket-actions.ts
  app/client/lib/date-formatter.ts
  app/client/lib/time-formatter.ts
  app/client/lib/utils.ts
  app/client/lib/validations.ts
  app/client/package.json
  app/client/store/useEventStore.ts
  app/client/types/types.d.ts
  app/client/yarn.lock
  app/server/src/controllers/eventController.ts
  app/server/src/index.ts
  app/server/src/models/eventSchema.ts
  app/server/src/routes/eventRoute.ts
Labels: bug, help wanted

#38 Create item detail page
  app/client/app/(dashboard)/categories/[itemId]/page.tsx
  app/client/app/(dashboard)/categories/components/categories-section.tsx
  app/client/app/(dashboard)/categories/components/category-card.tsx
  app/client/app/(dashboard)/categories/components/item-card.tsx
  app/client/app/(dashboard)/categories/components/item-detail.tsx
  app/client/app/(dashboard)/categories/components/item-list.tsx
  app/client/app/(dashboard)/categories/components/items-grid.tsx
  app/client/app/(dashboard)/categories/components/pagination.tsx
  app/client/app/(dashboard)/categories/components/sidebar.tsx
  app/client/app/(dashboard)/categories/components/sort-and-filter-bar.tsx
  app/client/app/(dashboard)/categories/components/testimonials.tsx
  app/client/app/(dashboard)/categories/page.tsx
  app/client/app/(dashboard)/checkout/components/checkout-form.tsx
  app/client/app/(dashboard)/checkout/components/stripe-provider.tsx
  app/client/app/(dashboard)/checkout/page.tsx
  app/client/app/(dashboard)/page.tsx
  app/client/app/organization/items/[id]/page.tsx
  app/client/app/organization/items/components/item-detail-section.tsx
  app/client/app/organization/items/components/photo-section.tsx
  app/client/app/organization/items/create/page.tsx
  app/client/app/organization/items/page.tsx
  app/client/components/checkout-ui/payment-content.tsx
  app/client/components/shop-maker.tsx
  app/client/components/star-rating.tsx
  app/client/components/ui/select.tsx
  app/client/components/ui/slider.tsx
  app/client/lib/actions/item-actions.ts
  app/client/next.config.ts
  app/client/package.json
  app/client/types/types.d.ts
  app/client/yarn.lock
  app/server/src/controllers/itemController.ts
  app/server/src/controllers/paymentController.ts
  app/server/src/controllers/sellerController.ts
  app/server/src/lib/validateSeller.ts
  app/server/src/models/itemSchema.ts
  app/server/src/routes/itemRoute.ts
  app/server/src/routes/paymentRoute.ts
  app/server/src/routes/sellerRoute.ts
Labels: bug, enhancement, dependencies

#43 improve landing page ui
  app/client/app/(dashboard)/components/carousel.tsx
  app/client/app/(dashboard)/components/category-icons.tsx
  app/client/app/(dashboard)/components/creatorcta.tsx
  app/client/app/(dashboard)/components/event-card.tsx
  app/client/app/(dashboard)/components/event-grid.tsx
  app/client/app/(dashboard)/components/event-tabs.tsx
  app/client/app/(dashboard)/components/locations.tsx
  app/client/app/(dashboard)/components/newletter.tsx
  app/client/app/(dashboard)/components/popular.tsx
  app/client/app/(dashboard)/components/smaller-card.tsx
  app/client/app/(dashboard)/components/upcoming.tsx
  app/client/app/(dashboard)/page.tsx
  app/client/app/organization/events/[eventId]/publish/page.tsx
  app/client/app/organization/events/[eventId]/ticket/components/ticket-day-picker.tsx
  app/client/app/organization/events/[eventId]/ticket/components/ticket-dialogs.tsx
  app/client/app/organization/events/[eventId]/ticket/components/ticket-form.tsx
  app/client/app/organization/events/[eventId]/ticket/components/ticket-ui.tsx
  app/client/app/organization/events/components/form-ui/date-location.tsx
  app/client/app/organization/events/components/form-ui/event-form-ui.tsx
  app/client/app/organization/events/components/form-ui/event-location.tsx
  app/client/app/organization/events/components/form-ui/event-photo.tsx
  app/client/app/organization/events/page.tsx
  app/client/app/organization/home/page.tsx
  app/client/constants/index.ts
  app/client/hooks/use-event.ts
  app/client/lib/actions/event-actions.ts
  app/client/package.json
  app/client/store/ticketStore.ts
  app/client/types/types.d.ts
  app/client/yarn.lock
  app/server/src/controllers/eventController.ts
  app/server/src/routes/eventRoute.ts
Labels: enhancement

#42 Create UserManual.md
  UserManual.md
Labels: documentation

#44 update README.md
  README.md
  app/client/app/(auth)/components/authform.tsx
  app/client/app/(auth)/verify-credential/page.tsx
  app/client/components/icons.tsx
  app/client/lib/actions/auth-actions.ts
  app/server/config/env.ts
  app/server/package.json
  app/server/src/controllers/authController.ts
  app/server/yarn.lock
Labels: enhancement
